# Setup
title:               Jason Abed
tagline:             'GitHub Pages'
description:         'Combining technology and creativity to make the world a better place.'
url:                 https://j-abed.github.io
baseurl:             ''
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Jason Abed
  url:               http://linkedin.com/in/jasonabed
  email:             jtabed @ gmail

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-34SMXHK93B

github:
  repo: https://github.com/j-abed/

instagram:
  user: jason_abed  # Instagram username

linkedin:
  user: jasonabed  # LinkedIn username